#Introduktion til "Numpy"

##Deep learning indenfor det sundhedstekniske domæne E23

Numpy er et python bibliotek som bruges til at arbejde med arrays. Numpy snvendes ofte når der i python arbejdes med eksempelvis liniar algebra, hvilket involverer matematiske operationer på vektorer og matricer og er en stor del af machine learning generalt, og i særdeleshed deep learning.

"Numpy" er et akronym for "Numerical Python" (ikke at det er vigtigt at huske på)

"List" klassen i python gør det ud for arrays (vektorer og matricer), men lister tager lang tid at processere i python, og som udgangspunkt er det ikke muligt at eksempelvis gange 2 lister på hinanden, lægge dem sammen elementvis etc. som man ville gøre med arrays uden at definere særligere funktioner til dette.

Numpy er udviklet specifikt til dette formål, og leverer significante tidsmæssige forbedringer for processering af arrays.

I kommer til at arbejde en del med Numpy i den første del af kurset, hvor i vil implementere nogle få, simple machine learning algoritmer "fra bunden" inden vi kaster os ud i brugen af specialiserede biblioteker. Dette er for at give jer en forståelse af nogle af de bagvedliggende matematiske operationer, og værdsætte behovet for brug at optimerede bibliotekter/algortimer

Numpy er installeret som standard i Colab, men hvis i arbejder med python lokalt, på jeres egen maskine, kræver det at Numpy installers enten i det (ikke anbefalet), eller isolerede (stærkt anbefalet), Python miljø.

Numpy installeres med Pythons package manager "pip" på følgende måde:


(her har jeg brugt "Anaconda" til at lave et isoleret python environment)

https://docs.anaconda.com/free/anaconda/install/index.html:

![Screenshot from 2023-08-30 11-14-09.png]()

##Numpy arrays

Array objekter i Numpy kaldes "ndarrays" og har en masse funktionaliteter som gør det relativt nemt og meget hurtigt at processere arrays. For at kunne arbejde med numpy i Python skal biblioteket først importeres:

In [ ]:
import numpy as np

#det er meget normalt at bruge aliaser såsom "np" for Numpy når man importerer et bibliotek i python.
#Så skal man ikke skrive hele navnet hver gang man skal bruge en metode eller klasse derfra

print('numpy version:',np.__version__)

In [ ]:
#basic numpy array. Som det ses her er
#egentlig bare en python liste som på en måde type castes til et numpy array.

arr = np.array([1,2,3,4])

print('array:',arr,'er af type',type(arr))

##N-dimensionelle arrays
Hvert numpy array har en "dimension" og en "shape".

Dimensioner angiver i hvor mange dimensioner array'et strækker sig i, og shape angiver udstrækningen i hver dimension

In [ ]:
# 0-D arrays i numpy er elementerne (skalarer) i et array. dvs. hvert element i et array er et 0-D array.
D_0 = np.array(25)

print(f'D_0 = {type(D_0)} med dimensioner {D_0.ndim} og shape på {D_0.shape} \n')

print(D_0)

# 1-D arrays som er en 1 x M matrice bestående af én række med M kolonner.
D_1 = np.array([1,2,3,4])

print(f'\n D_1 = {type(D_1)} med dimensioner {D_1.ndim} og shape på {D_1.shape}:')
print(D_1)

# 2-D arrays som er en M x N matrice bestående af M rækker med N kolonner.
D_2 = np.array([[1,2,3,4],[5,6,7,8]])

print('\n ')

print(f'D_2 = {type(D_2)} med dimensioner {D_2.ndim} og shape på {D_2.shape}:')
print(D_2)

# 3-D arrays som er en D x M x N  matrice bestående af D matricer med M rækker med N kolonner
D_3 = np.array([[[[1,2,3,4],[5,6,7,8]],
                [[9,10,11,12],[13,14,15,16]],[[9,10,11,12],[13,14,15,16]]]])

print('\n ')
print(f'D_3 = {type(D_3)} med dimensioner {D_3.ndim} og shape på {D_3.shape}:')
print(D_3)

D_5 = np.array([[1, 2, 3, 4],[5,6,7,8]], ndmin=5)

print('\n ')
print(f'D_5 = {type(D_5)} med dimensioner {D_5.ndim} og shape på {D_5.shape}:')
print(D_5)

##Indeksering af arrays
Arrays indeksering ligner det som kendes for python lister og tuples. Dvs. det første element i et array ligger på index 0.

In [ ]:
#indeksering i 2D arrays
arr = np.array([[1,2,3,4],[5,6,7,8]])

print(f'arr = {type(arr)} med dimensioner {arr.ndim} og shape på {arr.shape}')
print(arr)

print(f'1. array i arr = {arr[0]}')
print(f'2. array i arr = {arr[1]}')

print(f'1. element i arr 1. array = {arr[0,0]}')
print(f'2. element i arr 1. array = {arr[0,1]}')

In [ ]:
#indeksering i 3D arrays

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(f'arr = {type(arr)} med dimensioner {arr.ndim} og shape på {arr.shape}')
print('arr:')
print(arr)
print('\n')
#arr er et 3D array med 2, 2x3 arrays. Nedenfor printes det 3. element i den 2
#række i det første 2x3 array

print('arr[0, 1, 2]:')
print(arr[0, 1, 2])
print('\n')
#step 1:
print('step 1: arr[0]')
arr_0 = arr[0]
print(arr_0)
print('\n')
#step 2:
print('step 2: arr[0,1]')
arr_0_1 = arr_0[1]
print(arr_0_1)
print('\n')
#step 3:
print('step 3: arr[0,1,2]')
arr_0_1_2 = arr_0_1[2]
print(arr_0_1_2)

Negativ indeksering fungerer på samme møde som med lister

In [ ]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print('arr:')
print(arr)
print('\n')
print('arr[-1]:')
print(arr[-1])

##Array slicing

slicing af arrays er når man sampler/tilgår en mindre del af array. Ligesom indeksering, bare med flere elementer. Metoden en den samme som for almindelige python lister.

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

#slicing her tager alle elemnter fra det 2. element (index 1) op til, men eksklusiv, det 6. element (index 5)

print('arr[1:5]: \n')
print(arr[1:5])
print('\n')

#slicing her tager alle elemnter fra det 3. element (index 2) og det resterende array. Inklusiv det sidste element
print('arr[2:]: \n')
print(arr[2:])

##Numpy datatyper
I numpy findes de samme datatyper som i standard python:

- 'string', 'integer','float', 'boolean', 'complex'

Numpy inkluderer de samme datatyper og en del flere, men de vigtigste for os er:

- 'int' = interger (8, 16, 32, 64 bit precision)
- 'bool' = boolean
- 'uint' = unsigned integer (8, 16, 32, 64 bit precision)
- 'float' = float (8, 16, 32, 64, 128 bit precision)

Datatypen for et array kan checkes på følgende måde. Som standard er interger og float arrays 64 bit

In [ ]:
int_arr = np.array([1, 2, 3, 4])

print(int_arr.dtype)

float_arr = np.array([1., 2., 3., 4.])

print(float_arr.dtype)

Arrays kan initialiseres med en bestemt datatype, eller typecastes ligesom i standard python.

In [ ]:
print('8 bit interger array: \n')
arr = np.array([1, 2, 3, 4], dtype='int8')
print(arr, arr.dtype)
print('\n ')

print('16 bit interger array: \n')
arr = np.array([1, 2, 3, 4], dtype='int16')
print(arr, arr.dtype)

print('\n ')
print('128 bit float array: \n')
arr = np.array([1, 2, 3, 4], dtype='float128')
print(arr, arr.dtype)

print('\n ')
print('8 bit unsigned int array: \n')
arr = np.array([-1, 2, -3, 4], dtype='uint8')
print(arr, arr.dtype)

print('\n ')
print('bool array: \n')
arr = np.array([1, 2, 3, 0], dtype='bool')
print(arr, arr.dtype)

print('\n ')
print('64 bit float array type castet til 8 bit unsigned interger: \n')
arr = np.array([1., 2., 3., 4.])
print(arr,arr.dtype)
arr = arr.astype('uint8')
print(arr, arr.dtype)

Andre datatyper:

In [ ]:
#arrays kan også indeholde strings
arr = np.array([1, 2, 3, 4], dtype='str')
print(arr)
print(arr.dtype)

##Hvorfor er datatypen vigtig?

I nogle tilfælde kan det operationer med 2 eller flere arrays ikke lade sige gøre hvis ikke datatyperne stemmer overens. Nogle gange kunne man eksempelvis ønske at bruge et array til at "slice" et andet array.

In [ ]:
#array slice med integer indeks

arr = np.array([0,1,2,3,4])
slices = [1,3]
arr_slice = arr[slices]
print(arr_slice)

In [ ]:
#array slice med float indeks vil returnere en fejl
arr = np.array([0,1,2,3,4])
slices = [1.,3.]
arr_slice = arr[slices]
print(arr_slice)

Datatypen har også betydning hvor meget memory arrayet optager. Hvis man eksempelvis har et billede på 32x32 pixels med 3 farvekanaler (RGB). Så er der væsentlig forskel på hvor meget billedet fylder afhængigt af om det er 8 bit unsigned integer eller 32 bit float værdier. I nogle tilfælde vil det dog være nødvendigt at have en højere precision når man laver beregninger med arrays.

In [ ]:
print('8 bit interger array:')
#random image med 512x512x3 pixels med gråtoneværdier i range 0-255
image = np.random.randint(0,255,(512,512,3), dtype='uint8')

print('shape og type:',image.shape,image.dtype)

#antal af elementer 512x512x3:
print('størrelse:', image.size)

#memory størrelse for et enkelt element i bytes:
print('element memory størrelse:',image.itemsize)

#totale memory for hele billeder i megabytes:
print('samlet memory størrelse:',(image.itemsize*image.size)/1000**2)
print('\n')
print('32 bit float array:')
image = image.astype('float32')

print('shape og type:',image.shape,image.dtype)

#antal af elementer 512x512x3:
print('størrelse:', image.size)

#memory størrelse for et enkelt element i bytes:
print('element memory størrelse:',image.itemsize)

#totale memory for hele billeder i megabytes:
print('samlet memory størrelse:',(image.itemsize*image.size)/1000**2)

##Reshaping af arrays

In [ ]:
#1D array med 12 elementer til 2D array med 4x3 elementer
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
print('original array:\n',arr)
print('original shape:',arr.shape)


newarr = arr.reshape(4, 3)
print('\n nyt array:\n',newarr)
print('ny shape:',newarr.shape)

In [ ]:
#1D array med 12 elementer til 3D array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
print('original array:\n',arr)
print('original shape:',arr.shape)


newarr = arr.reshape(2,3,2)
print('\n nyt array:\n',newarr)
print('ny shape:',newarr.shape)

For at reshape et array fra én shape til en ny med bestemt størrelse skal antall af elementer i det oprindelige array stemme med størrelsen på det nye. Nedenfor vil funktionen returnere en fejl.

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print('original array:\n',arr)
print('original shape:',arr.shape)

#dette kald vil returnere en fejl
newarr = arr.reshape(3, 3)
print('\n nyt array:\n',newarr)
print('ny shape:',newarr.shape)

Andre reshape funktioner

In [ ]:
#1D array til 3D array med 2x2 elementer

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print('original array:\n',arr)
print('original shape:',arr.shape)

newarr = arr.reshape(2, 2, -1)
print('\n nyt array:\n',newarr)
print('ny shape:',newarr.shape)

In [ ]:
#Givent array til 1D array

arr = np.array([[1, 2, 3], [4, 5, 6]])
print('original array:\n',arr)
print('original shape:',arr.shape)

newarr = arr.reshape(-1)

print('\n ')
print('nyt array:\n',newarr)
print('ny shape:',newarr.shape)

#samme ide men med .flatten() metode
print('\n ')
newarr = arr.flatten()
print('flatten array:\n',newarr)
print('flatten shape:',newarr.shape)

#samme ide men med .ravel() metode

print('\n ')
newarr = arr.ravel()
print('ravel array:\n',newarr)
print('ravel shape:',newarr.shape)

##Iteration af arrays:
Iteration fungerer ligesom med python lister

In [ ]:
D1_arr = np.array([1, 2, 3])

print('1D array:')
for x in D1_arr:
  print(x)

print('\n')

D2_arr = np.array([[1, 2, 3], [4, 5, 6]])
print('D2 array:')
for x in D2_arr:
  print(x)

print('\n')

print('2D array nested loop')
for x in arr:
  for y in x:
    print(y)

#Andre array operationer:
- join (concatenate)
- split
- search
- sort
- filter

##Join
Med joining menes der at kombinere indholdet af to eller flere arrays i ét array. Concatenate funktionen kan bruges til at joine to arrays langs en given akse (default = 0)

In [ ]:
#Join af 2 arrays langs 1. akse (0)
print('inputs:')
arr1 = np.array([1, 2, 3])
print('arr1:',arr1,arr1.shape)

arr2 = np.array([4, 5, 6])
print('arr2:',arr2,arr2.shape)

print('outputs:')
arr = np.concatenate((arr1, arr2))
print('concatenate axis=0:',arr,arr.shape)

In [ ]:
#Join af 2, 2D arrays
print('inputs:')
arr1 = np.array([[1, 2], [3, 4]])
print('arr1:\n',arr1,arr1.shape)

arr2 = np.array([[5, 6], [7, 8]])
print('arr2:\n',arr2,arr2.shape)

arr = np.concatenate((arr1, arr2), axis=0)
print('concatenate axis=0:\n',arr,arr.shape)

arr = np.concatenate((arr1, arr2), axis=1)
print('concatenate axis=1:\n',arr,arr.shape)

##Stack
stacking er næsten det samme som concatenation. Forskellen er at stacking kan ske langs en ny akse. Dvs istedet for at joine 2, 1D arrays til et større 1D array, kan stacking bruges til at "stable" dem i et nyt 2D array.

In [ ]:
#stack 2, 1D arrays til 1, 2D array
print('inputs:')
arr1 = np.array([1, 2, 3])
print('arr1:',arr1,arr1.shape)

arr2 = np.array([4, 5, 6])
print('arr2:',arr2,arr2.shape)

print('outputs:')
arr = np.stack((arr1, arr2),axis=1)
print('stack axis=1:\n',arr,arr.shape)

Numpy har flere hjælpefunktioner til at "stacke" langs forskellige akser uden man explicet skal angive aksen i stack() funktionen.

In [ ]:
print('inputs:')
arr1 = np.array([1, 2, 3])
print('arr1:',arr1,arr1.shape)

arr2 = np.array([4, 5, 6])
print('arr2:',arr2,arr2.shape)

print('\n')
print('outputs:')
# h (horizontal) stack. Langs rækker:
arr = np.hstack((arr1, arr2))
print('hstack:',arr,arr.shape)
print('\n')
# v (vertical) stack. Langs kolonner:
arr = np.vstack((arr1, arr2))
print('vstack:\n',arr,arr.shape)
print('\n')
# d (vertical) stack. dybde:
arr = np.dstack((arr1, arr2))
print('dstack:\n',arr,arr.shape)

##Split
Omvendte operation af join. Splitter ét array op i N mindre arrays. Der findes 2 split funktioner i Numpy:
- split()
- array_split()

forskellen på split() og array_split() er at split kræver at antallet af elementer i det array man splitter kan fordeles ligeligt mellem de antal arrays der splittes i, men array_split ikke har denne constraint.

In [ ]:
#eksempel på split til 3 arrays med split() og array_split()
arr = np.array([1, 2, 3, 4, 5, 6])
print('input:', arr)

newarr = np.split(arr, 3)

print('split(arr,3) funktion:', newarr)

newarr = np.array_split(arr, 3)

print('array_split(arr,3) funktion:', newarr)

In [ ]:
#eksempel på split til 3 arrays med split() som fejler grundet ulige
#antal elementer i det initielle array
arr = np.array([1, 2, 3, 4, 5, 6,7])
print('input:', arr)

newarr = np.split(arr, 3)

print('split(arr,3) funktion:', newarr)

In [ ]:
#samme eksempel men med array_split()
arr = np.array([1, 2, 3, 4, 5, 6,7])
print('input:', arr)

newarr = np.array_split(arr, 3)

print('array_split(arr,3) funktion:', newarr)

##Search (np.where)

Der kan søges i et array for en given værdi hvorefter index hvor de værdier måtte eksistere returneres.

In [ ]:

arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

Returtypen ovenfor er en tuple som kan bruges til indekseren for eksempel til at slice et array

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(arr[x])

For 2D (eller flere dimensioner) returneres der det antal tuples som svare til antallet af dimensioner.

In [ ]:
arr = np.array([[1, 2, 3, 4],[1, 5, 4, 4]])

x = np.where(arr == 4)

print(x)

##Boolean array indeksering
Med boolean array indeksering kan der vælges elementer fra et array, baseret på
om elementet på det enkelte index opfylder en betingelse.

In [ ]:
import numpy as np

a = np.array([[1,2], [3, 4], [5, 6]])

 # Finder elementer som er større end 2
 # giver et numpy array med Booleans af samme shape
 # hvor hvert index fortæller hvorvidt elementet er > 2

bool_idx = (a > 2)

# Prints "[[False False]
#          [ True  True]
#          [ True  True]]"

print(bool_idx)

# boolean array indexing kan bruges til at konstruerer et rank 1 array
# bestående med elementer svarende til "True" elementerne i bool_idx
print(a[bool_idx])  # Printer "[3 4 5 6]"

#Operationen kan skrives i en linje:
print(a[a > 2])     # Printer "[3 4 5 6]"

##Sortering (np.sort)
Bruges til at arrangere elementer i et array i en ny ordnet sekvens:
- numerisk
- alfabetisk

In [ ]:
#numerisk sortering lav -> høj

arr = np.array([3, 2, 0, 1])
print('input:\n',arr)

print('output:\n',np.sort(arr))

In [ ]:
#alfabetisk a -> z
arr = np.array(['tre', 'to', 'nul', 'en'])
print('input:\n',arr)

print('output:\n',np.sort(arr))

##Sortering (np.argsort)
Istedet for at returnere det sorterede array returnerer argsort de index som ville som giver den korrekte sortering.

In [ ]:
#argsort lav -> høj

arr = np.array([3, 2, 0, 1,10, 4, 7, 6, 8, 5])
print('input:\n',arr)

print('output np.sort:\n',np.sort(arr))

print('output np.argsort:\n',np.argsort(arr))

print('output np.argsort til indeksering af usorterede array:\n',arr[np.argsort(arr)])

#Matematiske operationer i Numpy
Numpy inkluderer funktioner som virker elementvis på arrays:
- np.add()
- np.subtract()
- np.multiply()
- np.divide()
- np.sqrt()

Matematiske operationer på numpy arrays virker også med standard python operatorer ( + , - , * , / )

In [ ]:
import numpy as np

x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

# Elementvis sum; begge giver output:
# [[ 6.0  8.0]
#  [10.0 12.0]]
print('standard python + operator:')
print(x + y)
print('\n')
print('numpy function:')
print(np.add(x, y))

print('\n')
# Elementvis forskel; begge giver output
# [[-4.0 -4.0]
#  [-4.0 -4.0]]
print('standard python - operator:')
print(x - y)
print('\n')
print('numpy function:')
print(np.subtract(x, y))

print('\n')
# Elementvis multiplikation; begge giver output
# [[ 5.0 12.0]
#  [21.0 32.0]]
print('standard python * operator:')
print(x * y)
print('\n')
print('numpy function:')
print(np.multiply(x, y))

print('\n')
# Elementvis division; begge giver output
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print('standard python / operator:')
print(x / y)
print('\n')
print('numpy function:')
print(np.divide(x, y))

print('\n')
# Elementvis kvardratrod; giver output
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print('numpy np.sqrt() function:')
print(np.sqrt(x, y))

##Optimerede matematiske operationer med Numpy
som nævnt til at starte med, så er en de primære brug af Numpy i Python at gøre især matematiske operationer på arrays hurtigere. Til at illustre dette kan vi tage eksemplet nedenfor hvor to arrays ganges på hinanden elementvis for at give et nyt array. Vi sammenligner hastigheden for denne operation i ren python med Numpy implementeringen og forhåbentlig ser vi en forskel.

In [ ]:
# Ren Python kode til elementvis multiplikation af to lister (arrays)
# Naiv metode
import time

np.random.seed(10) #seed som skulle give os samme lister og resultat hver gang

#to lister (numpy arrays) med 1000 random intergers i range 0-255
list1 = np.random.randint(0,255,10000)
list2 = np.random.randint(0,255,10000)

print('list1 shape og dtype:',list1.shape,list1.dtype)

print ("første 10 elementer i list1 : ",list1[:10])
print ("første 10 elementer i list2 : ",list2[:10])

res_list = []
start = time.time()
for it in range(0,100):
  for i in range(0, len(list1)):
      res_list.append(list1[i] * list2[i])
slut = time.time()
print("Resultat (første 10 elementer): ", res_list[:10])

naiv_tid = (slut-start)/100

print('Gennemsnitstid for 100 iterationer af naiv metode:',naiv_tid)

In [ ]:
# Ren Python kode til elementvis multiplikation af to lister (arrays)
# list comprehension
import time

np.random.seed(10) #seed som skulle give os samme lister og resultat hver gang

#to lister (numpy arrays) med 1000 random intergers i range 0-255
list1 = np.random.randint(0,255,10000)
list2 = np.random.randint(0,255,10000)

print('list1 shape og dtype:',list1.shape,list1.dtype)

print ("første 10 elementer i list1 : ",list1[:10])
print ("første 10 elementer i list2 : ",list2[:10])

res_list = []
start = time.time()
for it in range(0,100):
  res_list = [list1[i] * list2[i] for i in range(len(list1))]

slut = time.time()
print("Resultat (første 10 elementer): ", res_list[:10])

lc_tid = (slut-start)/100

print('Gennemsnitstid for 100 iterationer af list comprehension:',lc_tid)

In [ ]:
# Numpy kode til elementvis multiplikation af to lister (arrays)

import time

np.random.seed(10) #seed som skulle give os samme lister og resultat hver gang

#to lister (numpy arrays) med 1000 random intergers i range 0-255
list1 = np.random.randint(0,255,10000)
list2 = np.random.randint(0,255,10000)

print('list1 shape og dtype:',list1.shape,list1.dtype)

print ("første 10 elementer i list1 : ",list1[:10])
print ("første 10 elementer i list2 : ",list2[:10])

res_list = []
start = time.time()
for it in range(0,100):
  res_list = np.multiply(list1, list2)

slut = time.time()
print("Resultat (første 10 elementer): ", res_list[:10])

np_tid = (slut-start)/100

print('gennemsnitstid for 100 iterationer af numpy multiply:',slut-start)

In [ ]:
print('list comprehension speed-up:',naiv_tid/lc_tid)
print('numpy speed-up:',naiv_tid/np_tid)

##np.dot

np.multiply og Pythons * operator giver en elementvis multiplikation af to arrays. Prikproduktet, eller det indre produkt udregnes med np.dot, og operation anvendes hyppigt inden for machine learning og deep learning til eksempelvis at gange et input på et set af modelparametre hvilket udtrykker modellens respons på det givne input.

In [ ]:
import numpy as np

x = np.array([[1,2],
              [3,4]])
y = np.array([[5,6],
              [7,8]])

v = np.array([9,10])
w = np.array([11, 12])

print('Indre produkt af vektorer; begge giver 219')

print(v.dot(w))
print(np.dot(v, w))
print('\n')
print('Matrix / vector produkt; begge giver rank 1 array [29 67]')

print(x.dot(v))
print(np.dot(x, v))
print('\n')
print('Matrix / matrix product; begge giver et rank 2 array [[19 22][43 50]]')

print(x.dot(y))
print(np.dot(x, y))

##np.sum()
en anden meget anvendelig funktion i numpy som kan udrende summen af et array, både hele arrayet og langs en given akse.

In [ ]:
x = np.array([[1,2],[3,4]])

print('sum of alle elementer; printer 10')
print(np.sum(x))
print('\n')
print('sum af hver søjle/kolonne; printer "[4 6]"')
print(np.sum(x, axis=0))
print('\n')
print('sum af hver række; printer "[3 7]"')
print(np.sum(x, axis=1))
print('\n')

##Array manipulation
Vi har allerede gennemgået hvordan et numpy array kan "reshapes", men numpy inkluderer andre operatiner på arrays som kan ændre deres form eller composition på andre måder. To væsentlige operationer som i vil støde på i starten af kurset er:

##Transpose:
- np.transpose() (.T kan også bruges direkte på arrayet)

In [ ]:
x = np.array([[1,2], [3,4]])

print('printer x "[[1 2][3 4]]')
print(x)
print('\n')
print('printer x.T "[[1 3][2 4]]"')
print(x.T)
print('\n')
print('printer np.transpose(x) "[[1 3][2 4]]"')
print(np.transpose(x))
print('\n')
print('transpose af rank 1 array ændre ikke på arrayet:')
v = np.array([1,2,3])
print('\n')
print('printer v "[1 2 3]"')
print(v)
print('\n')
print('printer v.T "[1 2 3]"')
print(v.T)

##Broadcasting
Er ikke en funktion men nærmere en mekanisme indbygget i numpy som tillader at der laves operationer med arrays af forskellige shapes. Broadcasting kommer i spil eksempelvis hvis man har et mindre array og et større array hvor der skal udføres flere operationer på det store array med det mindre array.

Hvis man eksempel ville lægge en konstant vektor til hver række i en matrix kunne den naive metode (uden brug af broadcasting) men "for loops" se ud som nedenfor.

Metoden virker, men for meget store arrays vil det tage lang tid. som eksempelet med array multiplikation tidligere viste.

In [ ]:

# vektoren v lægges til hver række i matrix x
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
# der laves et tomt array med sammee shape som x
y = np.empty_like(x)

# Vector v lægges til hver række i x vha. af loops
for i in range(4):
    y[i, :] = x[i, :] + v

# Nu er y:
# [[ 2  2  4]
#  [ 5  5  7]
#  [ 8  8 10]
#  [11 11 13]]
print(y)

Man kunne opnå samme resultat ved at lave kopier af v og indsætte i en matrix med samme shape som x. Men dette er stadig ikke en særlig effiktiv tilgang.

Med numpy broadcasting kan operationen laves uden loops eller eksplicite kopier af v:

In [ ]:
#Læg vektor v til hver række i x. broadcasting mekanismen i numpy
#gør dette simpelt og effektivt.


x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])

# v + hver række i x med broadcasting
y = x + v
print(y)

##Generelt om broadcasting
(fra https://cs231n.github.io/python-numpy-tutorial/#numpy)

Broadcasting two arrays together follows these rules:

  - If the arrays do not have the same rank, prepend the shape of the lower rank array with 1s until both shapes have the same length.
  - The two arrays are said to be compatible in a dimension if they have the same size in the dimension, or if one of the arrays has size 1 in that dimension.
  - The arrays can be broadcast together if they are compatible in all dimensions.
  - After broadcasting, each array behaves as if it had shape equal to the elementwise maximum of shapes of the two input arrays.
  - In any dimension where one array had size 1 and the other array had size greater than 1, the first array behaves as if it were copied along that dimension

If this explanation does not make sense, try reading the explanation from the documentation or this explanation.

Functions that support broadcasting are known as universal functions. You can find the list of all universal functions in the documentation.

##Eksempler på brug af broadcasting
(fra https://cs231n.github.io/python-numpy-tutorial/#numpy)

In [ ]:
import numpy as np

# Compute outer product of vectors
v = np.array([1,2,3])  # v has shape (3,)
w = np.array([4,5])    # w has shape (2,)
# To compute an outer product, we first reshape v to be a column
# vector of shape (3, 1); we can then broadcast it against w to yield
# an output of shape (3, 2), which is the outer product of v and w:
# [[ 4  5]
#  [ 8 10]
#  [12 15]]
print(np.reshape(v, (3, 1)) * w)

# Add a vector to each row of a matrix
x = np.array([[1,2,3], [4,5,6]])
# x has shape (2, 3) and v has shape (3,) so they broadcast to (2, 3),
# giving the following matrix:
# [[2 4 6]
#  [5 7 9]]
print(x + v)

# Add a vector to each column of a matrix
# x has shape (2, 3) and w has shape (2,).
# If we transpose x then it has shape (3, 2) and can be broadcast
# against w to yield a result of shape (3, 2); transposing this result
# yields the final result of shape (2, 3) which is the matrix x with
# the vector w added to each column. Gives the following matrix:
# [[ 5  6  7]
#  [ 9 10 11]]
print((x.T + w).T)
# Another solution is to reshape w to be a column vector of shape (2, 1);
# we can then broadcast it directly against x to produce the same
# output.
print(x + np.reshape(w, (2, 1)))

# Multiply a matrix by a constant:
# x has shape (2, 3). Numpy treats scalars as arrays of shape ();
# these can be broadcast together to shape (2, 3), producing the
# following array:
# [[ 2  4  6]
#  [ 8 10 12]]
print(x * 2)

##Slutnote

Eksemplerne i denne notebook er inspireret af:

https://www.w3schools.com/python/numpy/default.asp

og:

https://cs231n.github.io/python-numpy-tutorial/#numpy

Notebooken er på ingen måde fyldestgørende og der kan findes mangle flere eksempler og forklaringer her:

https://numpy.org/doc/stable/reference/